# Generated by Django 3.2.4 on 2021-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intermediateVerficationModal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('verificationStatus', models.BooleanField()),
                ('otp', models.CharField(max_length=1000)),
            ],
        ),
    ]
