# Generated by Django 3.2.6 on 2021-10-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogcodecs', '0009_comments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=100)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcodecs.blogs')),
            ],
        ),
    ]
